BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PREREQUISITE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE GRADE_REPORT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE SECTION';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE COURSE';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE STUDENT';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE STUDENT (
 Name VARCHAR(20) NOT NULL,
 Student_number INT CHECK (Student_number > 0),
 Class INT NOT NULL CHECK (Class > 0),
 Major VARCHAR(10),
 PRIMARY KEY (Student_number));
 
 CREATE TABLE COURSE (
 Course_name VARCHAR(30) NOT NULL,
 Course_number VARCHAR(10) NOT NULL,
 Credit_hours INT NOT NULL CHECK (Credit_hours > 0),
 Department VARCHAR(10) NOT NULL,
 PRIMARY KEY (Course_number));
 
 CREATE TABLE SECTION (
 Section_identifier INT NOT NULL CHECK (Section_identifier > 0),
 Course_number VARCHAR(10) NOT NULL,
 Semester VARCHAR(10) NOT NULL CHECK (Semester IN ('Fall', 'Spring', 'Summer')),
 Year DATE,
 Instructor VARCHAR(20) NOT NULL,
 PRIMARY KEY (Section_identifier),
 FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number));
 
 CREATE TABLE GRADE_REPORT (
 Student_number INT NOT NULL CHECK (Student_number > 0),
 Section_identifier INT NOT NULL CHECK (Section_identifier > 0),
 Grade VARCHAR(10),
 FOREIGN KEY (Student_number) REFERENCES STUDENT(Student_number),
 FOREIGN KEY (Section_identifier) REFERENCES SECTION(Section_identifier));
 
 CREATE TABLE PREREQUISITE (
 Course_number VARCHAR(10) NOT NULL,
 Prerequisite_number VARCHAR(10),
 FOREIGN KEY (Course_number) REFERENCES COURSE(Course_number),
 FOREIGN KEY (Prerequisite_number) REFERENCES COURSE(Course_number));
 
